test_0 (__main__.lab2a.test_0)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for file creation: ./lab2a.py ... ok
test_1 (__main__.lab2a.test_1)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for errors running: ./lab2a.py ... /usr/lib/python3.12/subprocess.py:822: ResourceWarning: unclosed file <_io.TextIOWrapper name=3 encoding='UTF-8'>
  _cleanup()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_2 (__main__.lab2a.test_2)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct shebang line: ./lab2a.py ... ok
test_3 (__main__.lab2a.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - variables & printing - Test for correct output: ./lab2a.py ... ok
test_0 (__main__.lab2b.test_0)
[Lab 2] - [Investigation 1] - [Part 1] - using input() function - Test for file creation: ./lab2b.py ... ok
test_1 (__main__.lab2b.test_1)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test for errors with sending input "Jon" "20": ./lab2b.py ... ok
test_2 (__main__.lab2b.test_2)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test for correct shebang line: ./lab2b.py ... ok
test_3 (__main__.lab2b.test_3)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test output with sending input "Jon" "20": ./lab2b.py ... ok
test_4 (__main__.lab2b.test_4)
[Lab 2] - [Investigation 1] - [Part 1] - using input() - Test output with sending input "Jen" "25": ./lab2b.py ... ok
test_0 (__main__.lab2c.test_0)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for file creation: ./lab2c.py ... ok
test_1 (__main__.lab2c.test_1)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for errors with 2 args: ./lab2c.py Jon 20 ... ok
test_2 (__main__.lab2c.test_2)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test for correct shebang line: ./lab2c.py ... ok
test_3 (__main__.lab2c.test_3)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test output for: ./lab2c.py Jon 20 ... ok
test_4 (__main__.lab2c.test_4)
[Lab 2] - [Investigation 1] - [Part 2] - command line arguments - Test output for: ./lab2c.py Jen 25 ... ok
test_0 (__main__.lab2d.test_0)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for file creation: ./lab2d.py ... ok
test_1 (__main__.lab2d.test_1)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for errors with 0 args: ./lab2d.py ... ok
test_2 (__main__.lab2d.test_2)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for correct shebang line: ./lab2d.py ... FAIL

======================================================================
FAIL: test_2 (__main__.lab2d.test_2)
[Lab 2] - [Investigation 2] - [Part 1] - sys.argv and if - Test for correct shebang line: ./lab2d.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jgylagan/ops445/lab2/lab-2-JohnGabrielYlagan/./CheckLab2.py", line 194, in test_2
    self.assertEqual(first_line.strip(), '#!/usr/bin/env python3', msg=error_output)
AssertionError: '' != '#!/usr/bin/env python3'
+ #!/usr/bin/env python3
 : your program does not have a correct shebang line (HINT: what should the first line contain)

----------------------------------------------------------------------
Ran 17 tests in 0.087s

FAILED (failures=1)
OPS445 Lab Report - System Information for running ./CheckLab2.py
=================================================================
    User login name: jgylagan
    Git Email: jgylagan@myseneca.ca
    Linux system name: jgylaganOPS445
    Python executable: /usr/bin/python3
    Python version:  3.12.3 (main, Feb  4 2025, 14:48:35) [GCC 13.3.0]
    OS Platform: linux
    Working Directory: /home/jgylagan/ops445/lab2/lab-2-JohnGabrielYlagan
    Start at: Fri May 23 14:34:11 2025
=================================================================
